[project]
name = "duck-ui5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
]
